pages:
  stage: deploy
  script:
    - npm ci
    - npm run build
    - Copy-Item dist/index.html dist/404.html
    - if (Test-Path public) { Remove-Item -Recurse -Force public }
    - Move-Item dist public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
